/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.gui;

import javax.swing.JOptionPane;
import pidev.dao.EvaluationDAO;
import pidev.entities.Affectation;
import pidev.entities.Evaluation;
import pidev.entities.Freelancer;
import pidev.entities.User;
import pidev.interfaces.IEvaluationDAO;
import pidev.modeles.ModeleFreelancerSearch;

/**
 *
 * @author SaddeM
 */
public class FrameFindetEvaluer extends javax.swing.JFrame {

    
    /**
     * Creates new form FrameFindetEvaluer
     */
    public FrameFindetEvaluer() {
        initComponents();
        evaluAte.setValue(0);
      
        
    }
    public void remplirTxt(String txtMe){
        SearchPro2.setText(txtMe);
        jTable1.setModel(new ModeleFreelancerSearch(txtMe));
    }
     
  
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchPro2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        evaluAte = new javax.swing.JSlider();
        etoile1 = new javax.swing.JLabel();
        etoile2 = new javax.swing.JLabel();
        etoile3 = new javax.swing.JLabel();
        etoile4 = new javax.swing.JLabel();
        etoile5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        saySomeTxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 400));

        jTable1.setModel(new ModeleFreelancerSearch(""));
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        jScrollPane1.setViewportView(jTable1);

        SearchPro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPro2ActionPerformed(evt);
            }
        });
        SearchPro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchPro2KeyReleased(evt);
            }
        });

        jLabel1.setText("Search");

        jButton1.setText("Evaluer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        evaluAte.setMaximum(5);
        evaluAte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluAteMouseClicked(evt);
            }
        });

        etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png"))); // NOI18N

        etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png"))); // NOI18N

        etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png"))); // NOI18N

        etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png"))); // NOI18N

        etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png"))); // NOI18N

        saySomeTxt.setColumns(20);
        saySomeTxt.setRows(5);
        jScrollPane2.setViewportView(saySomeTxt);

        jLabel2.setText("Say something");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(SearchPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(evaluAte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(etoile1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etoile2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etoile3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etoile4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etoile5))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etoile1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etoile3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etoile4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etoile5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(evaluAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(etoile2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchPro2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchPro2KeyReleased
        jTable1.setModel(new ModeleFreelancerSearch(SearchPro2.getText()));
    }//GEN-LAST:event_SearchPro2KeyReleased

    private void SearchPro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchPro2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int a=jTable1.getSelectedRow();
        
         if (a!=-1)
         {       
            Freelancer fFf = new Freelancer();
            fFf = (Freelancer)jTable1.getValueAt(a, 5);
            
            //XX113XX id user ici 3
            User eValuant = new User(3, "", "", "", "", "", "", "", 0, "", 0);
            //en haut
            
            User eValuer = new User(fFf.getId(), "", "", "", "", "", "", "", 0, "", 0);
            Evaluation eee = new Evaluation(saySomeTxt.getText(), evaluAte.getValue(), eValuant, eValuer, "aze");
            IEvaluationDAO edaoo = EvaluationDAO.getInstance();
            edaoo.insertEvaluation(eee);
            JOptionPane.showMessageDialog(this, "Evaluatin effectué", "FreeRequests", JOptionPane.INFORMATION_MESSAGE);
             
 
         }
         else
              JOptionPane.showMessageDialog(this, "Selectionner une requete", "FreeRequests", JOptionPane.ERROR_MESSAGE);
             
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void evaluAteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluAteMouseClicked
        System.out.println(evaluAte.getValue());
        switch(evaluAte.getValue()){
            case 0:
            etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
          return;
        case 1:
            etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            
            etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
          
            return;
        case 2: 
           etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
           etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
           
           return;
        case 3: 
            etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
           
            return;
        case 4: 
            etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_tafia.png")));
            
            return;
        case 5: 
            etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
            etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/etoile_che3la.png")));
          
            return;
        }
    }//GEN-LAST:event_evaluAteMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFindetEvaluer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFindetEvaluer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFindetEvaluer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFindetEvaluer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new FrameFindetEvaluer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchPro2;
    private javax.swing.JLabel etoile1;
    private javax.swing.JLabel etoile2;
    private javax.swing.JLabel etoile3;
    private javax.swing.JLabel etoile4;
    private javax.swing.JLabel etoile5;
    private javax.swing.JSlider evaluAte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea saySomeTxt;
    // End of variables declaration//GEN-END:variables
}
