/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.gui;



import java.awt.BorderLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import pidev.dao.AffectationDAO;
import pidev.dao.CommentaireDAO;
import pidev.dao.DomaineDAO;
import pidev.dao.FreelancerDAO;
import pidev.dao.MessageDAO;
import pidev.dao.ProjetDAO;
import pidev.dao.QuestionDAO;
import pidev.dao.SousDomaineDAO;
import pidev.entities.Projet;
import pidev.dao.UserDAO;
import pidev.entities.Affectation;
import pidev.entities.Commentaire;
import pidev.entities.Domaine;
import pidev.entities.Freelancer;
import pidev.entities.Grade;
import pidev.entities.Question;
import pidev.entities.SousDomaine;
import pidev.entities.User;
import pidev.interfaces.IAffectationDAO;
import pidev.interfaces.ICommentaireDAO;
import pidev.interfaces.IDomaineDAO;
import pidev.interfaces.IFreelancerDAO;
import pidev.interfaces.IMessageDAO;
import pidev.interfaces.IProjetDAO;
import pidev.interfaces.IQuestionDAO;
import pidev.interfaces.ISousDomaineDAO;
import pidev.interfaces.IUserDAO;
import pidev.modeles.*;


/**
 *
 * @author HP
 */
public class FrameFreeLancer extends javax.swing.JFrame {

    String uri; 
    /**
     * Creates new form FrameFreeLancer
     */
    public FrameFreeLancer() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_pwd = new javax.swing.JPasswordField();
        tf_lname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_fname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        TxtA_affectationDetails = new javax.swing.JEditorPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        sous_domainesList = new javax.swing.JList();
        jButton10 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        affectation = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        comment_project = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        domaineForTest = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu7.setText("jMenu7");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setText("Welcome FreeLancer's Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 10, 310, 23);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel2.setText("You have 500 Tokens");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 30, 156, 25);

        jComboBox1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jobs", "JobOwners" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(370, 80, 100, 31);

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(480, 80, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/hardware-icon-search-button.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 80, 28, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/logout.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 0, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/téléchargement.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 730, 140);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 320, 0, 0);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(552, 50));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(552, 50));

        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Curriculum Vitae");

        tf_lname.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Email");

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Password");

        tf_fname.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("First Name");

        jTextField6.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Date Of Birth");

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Last Name");

        tf_email.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel15))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_fname)
                            .addComponent(tf_lname)
                            .addComponent(tf_email)
                            .addComponent(tf_pwd)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(240, 10, 340, 280);

        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 130, 130);

        jButton1.setText("Choisir Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 140, 130, 40);

        jButton5.setText("Download Curriculum Vitae");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(40, 240, 170, 40);

        jTabbedPane2.addTab("My Profile", jPanel2);

        jPanel4.setLayout(null);

        jTable1.setModel(new ModeleAffectation(1));
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 630, 100);

        jLabel8.setText("Details");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(50, 170, 32, 14);

        jButton11.setText("More details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);
        jButton11.setBounds(150, 110, 230, 30);

        jScrollPane10.setViewportView(TxtA_affectationDetails);

        jPanel4.add(jScrollPane10);
        jScrollPane10.setBounds(120, 170, 330, 200);

        jTabbedPane2.addTab("Manage Projects", jPanel4);

        jPanel5.setLayout(null);

        jLabel10.setText("Domain");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(70, 34, 70, 30);

        jLabel11.setText("Sub domain");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(70, 100, 90, 30);

        jComboBox2.addItem("");
        IDomaineDAO ddao = DomaineDAO.getInstance();

        for (Domaine d:ddao.DisplayAllDomaines()){

            jComboBox2.addItem(d);
        }
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(180, 30, 250, 30);

        jScrollPane3.setViewportView(sous_domainesList);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(180, 100, 250, 130);

        jButton10.setText("Submit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(180, 260, 250, 23);

        jTabbedPane2.addTab("Manage Domains", jPanel5);

        jPanel6.setLayout(null);

        jTabbedPane3.setForeground(new java.awt.Color(0, 102, 102));

        jTable2.setModel(new ModeleMessageRecieve());
        jScrollPane4.setViewportView(jTable2);

        jTabbedPane3.addTab("Inbox", jScrollPane4);

        jTable3.setModel(new ModeleMessageSent());
        jScrollPane5.setViewportView(jTable3);

        jTabbedPane3.addTab("Sent Mail", jScrollPane5);

        jPanel6.add(jTabbedPane3);
        jTabbedPane3.setBounds(0, 0, 457, 160);

        jButton4.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(430, 190, 130, 30);

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("From");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(100, 290, 39, 17);
        jPanel6.add(jTextField2);
        jTextField2.setBounds(170, 320, 110, 20);
        jPanel6.add(jTextField3);
        jTextField3.setBounds(170, 350, 110, 20);

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("To");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(120, 320, 19, 17);

        jLabel20.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Date");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(110, 350, 35, 17);
        jPanel6.add(jTextField5);
        jTextField5.setBounds(170, 290, 110, 20);

        jLabel21.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 51));
        jLabel21.setText("Message");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(80, 180, 62, 17);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        jPanel6.add(jScrollPane6);
        jScrollPane6.setBounds(170, 170, 190, 110);

        jTabbedPane2.addTab("Messages", jPanel6);

        jPanel7.setLayout(null);

        jTable4.setModel(new ModeleProjet());
        jTable4.getColumnModel().getColumn(3).setMaxWidth(0);
        jTable4.setFillsViewportHeight(true);
        jScrollPane7.setViewportView(jTable4);

        jPanel7.add(jScrollPane7);
        jScrollPane7.setBounds(0, 0, 610, 110);

        jButton6.setText("Comment Project");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(70, 280, 140, 40);

        jButton7.setText("Ask for Affectation");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(420, 280, 140, 40);

        affectation.setColumns(20);
        affectation.setRows(5);
        jScrollPane8.setViewportView(affectation);

        jPanel7.add(jScrollPane8);
        jScrollPane8.setBounds(370, 190, 250, 80);

        jLabel22.setText("Are you intrested ?");
        jPanel7.add(jLabel22);
        jLabel22.setBounds(370, 170, 150, 14);

        comment_project.setColumns(20);
        comment_project.setRows(5);
        jScrollPane9.setViewportView(comment_project);

        jPanel7.add(jScrollPane9);
        jScrollPane9.setBounds(20, 190, 250, 80);

        jLabel23.setText("Say something about the project...");
        jPanel7.add(jLabel23);
        jLabel23.setBounds(20, 170, 200, 14);

        jButton8.setText("See all comments");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8);
        jButton8.setBounds(70, 330, 140, 30);

        jButton9.setText("Details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9);
        jButton9.setBounds(20, 120, 580, 23);

        jTabbedPane2.addTab("Actualities", jPanel7);

        jPanel3.setLayout(null);

        domaineForTest.addItem("");

        for (Domaine d:ddao.DisplayAllDomaines()){

            domaineForTest.addItem(d);
        }
        domaineForTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domaineForTestActionPerformed(evt);
            }
        });
        jPanel3.add(domaineForTest);
        domaineForTest.setBounds(210, 60, 140, 50);

        jButton3.setText("Passer le test");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(210, 150, 140, 60);

        jTabbedPane2.addTab("Tests", jPanel3);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 140, 730, 420);

        jMenu1.setForeground(new java.awt.Color(0, 102, 102));
        jMenu1.setText("Profile");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/exit.png"))); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 102, 102));
        jMenu2.setText("Projects");

        jMenuItem10.setText("All");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("My Work");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu3.setForeground(new java.awt.Color(0, 102, 102));
        jMenu3.setText("Messages");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Inbox");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem8.setText("Sent Mail");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 102, 102));
        jMenu4.setText("JobOwners");

        jMenuItem9.setText("Show");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(0, 102, 102));
        jMenu5.setText("Settings");

        jMenuItem1.setText("Edit Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(0, 102, 102));
        jMenu6.setText("Help");

        jMenuItem5.setText("Help Contents");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);
        jMenu6.add(jSeparator1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("About");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem7.setText("Version Information");
        jMenu6.add(jMenuItem7);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
       InboxFrame i = new InboxFrame();
       this.setVisible(false);
       i.setVisible(true);
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String format = "dd/MM/yyyy";
        SimpleDateFormat formater = new SimpleDateFormat(format);
        java.util.Date dd = jDateChooser1.getDate();
        String d = (formater.format(dd)).toString();

        String name = tf_fname.getText();
        String lname = tf_lname.getText();
        String email = tf_email.getText();
        String pwd = tf_pwd.getText();

        User u = new User();
        u.setId(20);
        u.setPrenom(name);
        u.setNom(lname);
        u.setEmail(email);
        u.setDate_naissance(d);
        u.setPassword(pwd);
        IUserDAO udao = UserDAO.getInstance();
        udao.updateUserProfile(u);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser chooser = new JFileChooser();
        String uri =null;  
        chooser.setApproveButtonText("Choix du fichier");
        //affiche la boite de dialogue 
        chooser.showOpenDialog(null);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
           uri = chooser.getSelectedFile().getAbsolutePath();
        }
        File image = new File(uri);
        try {
            FileInputStream f = new FileInputStream(image);
        } catch (FileNotFoundException ex) {
           
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         int a=jTable4.getSelectedRow();
         if (a!=-1)
         {       
       IProjetDAO pdao = ProjetDAO.getInstance();
       Projet projet = new Projet();
            projet = (Projet)jTable4.getValueAt(a, 3);
            
            IUserDAO udao = UserDAO.getInstance();
            User u = new User();
            u = udao.FindUserById(projet.getUser().getId());
             
            ICommentaireDAO cdao = CommentaireDAO.getInstance();
            
            Commentaire c = new Commentaire(projet, u, comment_project.getText(), "");
            cdao.insertCommentaire(c);
            
             JOptionPane.showMessageDialog(comment_project, "Commentaire ajoutée", "Commentaire", JOptionPane.INFORMATION_MESSAGE);
           
         }
         else
             JOptionPane.showMessageDialog(comment_project, "Veillez selectionner un projet", "Commentaire", JOptionPane.ERROR_MESSAGE);
           
         
       
         
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         int a=jTable4.getSelectedRow();
         if (a!=-1)
         {       
       IProjetDAO pdao = ProjetDAO.getInstance();
       Projet projet = new Projet();
            projet = (Projet)jTable4.getValueAt(a, 3);
            
            //En principe on prendra le freelancer déja connecté mais je vais faire une instance pour le mettre en marche
            IFreelancerDAO fdao = FreelancerDAO.getInstance();
            Freelancer f = new Freelancer();
            f = fdao.FindFreelancerById(4);
             
            IAffectationDAO adao = AffectationDAO.getInstance();
            Affectation aff = new Affectation(projet, f, 0, 0, "");
            adao.AffecterFreelancer(aff);
  
            
             JOptionPane.showMessageDialog(comment_project, "Affectation ajoutée", "Affectation", JOptionPane.INFORMATION_MESSAGE);
           
         }
         else
             JOptionPane.showMessageDialog(comment_project, "Veillez selectionner une information", "Affectation", JOptionPane.ERROR_MESSAGE);
           
         
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     int a=jTable4.getSelectedRow();
         if (a!=-1)
         {       
       IProjetDAO pdao = ProjetDAO.getInstance();
       Projet projet = new Projet();
            projet = (Projet)jTable4.getValueAt(a, 3);
            
           ICommentaireDAO cdao = CommentaireDAO.getInstance();
           
        FrameSeeAllComments fComs = new FrameSeeAllComments(cdao.FindCommentaireByIdProjet(projet.getId()));
        fComs.setVisible(true);
        
         }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    int a=jTable4.getSelectedRow();
         if (a!=-1)
         {       
            
            Projet projet = new Projet();
            projet = (Projet)jTable4.getValueAt(a, 3);
             System.out.println(projet.getDetails());
           
        FrameDetailsProject fDet = new FrameDetailsProject(projet);
        fDet.setVisible(true);
        
         }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

            if (jComboBox2.getSelectedIndex()!=0){
        Domaine Dom = (Domaine)jComboBox2.getSelectedItem();
        
         ISousDomaineDAO sdao = SousDomaineDAO.getInstance();
         List<SousDomaine> allSousDomaines = sdao.findSousDomaineByIdDom(Dom.getId());
         List<SousDomaine> allSousDomainesFreelancer = sdao.findSousDomaineByIdFreelancer(1);
         DefaultListModel modelz = new DefaultListModel();
         for(SousDomaine soudomaine : allSousDomaines){
             modelz.addElement(soudomaine);
         }
         
         sous_domainesList.setModel(modelz);
         
        List<Integer> indices = new ArrayList();
        
        int j = 0;
         for(Object object : modelz.toArray()){
             SousDomaine souDomaine = (SousDomaine) object;
             if(allSousDomainesFreelancer.contains(souDomaine)){
                 indices.add(j);
              
             }
             j++;
         }
         
         int[] indicess = new int[indices.size()];
         int k = 0 ;
            for (Integer l : indices){
                indicess[k]=l;
                k++;
            }
            
             sous_domainesList.setSelectedIndices(indicess);
         
         
        
        }
        else{
            JOptionPane.showMessageDialog(comment_project, "Veillez selectionner un domaine", "Domaines", JOptionPane.ERROR_MESSAGE);
           
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         if (sous_domainesList.getSelectedIndex() !=-1){
             List<SousDomaine> sdomaines = new ArrayList<SousDomaine>();
             sdomaines = sous_domainesList.getSelectedValuesList();
           IFreelancerDAO ffdao = FreelancerDAO.getInstance();
           
           // XX113XX l'id du freelancer est 1 mais elle changera aprés celon le fl connecté
           ffdao.insertDomaine_Freelancer(1, sdomaines);
         JOptionPane.showMessageDialog(comment_project, "Modification effectuée", "Sous-domaines", JOptionPane.INFORMATION_MESSAGE);
              
         }
         else{
              JOptionPane.showMessageDialog(comment_project, "Modification effectuée", "Sous-domaines", JOptionPane.INFORMATION_MESSAGE);
              IFreelancerDAO ffdao = FreelancerDAO.getInstance();
              Domaine d = (Domaine)jComboBox2.getSelectedItem();
              
              ffdao.deleteDomaine_Freelancer(1,d);
         }
         
        
       
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       int a=jTable1.getSelectedRow();
         if (a!=-1)
         {       
            
            Affectation affectation = new Affectation();
            affectation = (Affectation)jTable1.getValueAt(a, 4);
           
        TxtA_affectationDetails.setText(affectation.getProjet().getDetails());
        
         }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Domaine DomTest = new Domaine();
        DomTest = (Domaine)domaineForTest.getSelectedItem();
        FrameExamen fe = new FrameExamen();
        fe.setD(DomTest);
        //XX113XX ici Freelancer
        Freelancer f = new Freelancer("", new Grade(), 1, "", "", "", "", "", "", "", 1, "", 50);
        fe.setF(f);
        
        IQuestionDAO qdao = QuestionDAO.getInstance();
        List<Question> qs = new ArrayList<Question>();
        System.out.println(DomTest.getId());
        qs = qdao.DisplayAllQuestionsRepsByIdDomaine(DomTest.getId());
        
        fe.remplir(qs, 0);
        
        fe.setVisible(true);
       
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void domaineForTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domaineForTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domaineForTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFreeLancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFreeLancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFreeLancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFreeLancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameFreeLancer fr = new FrameFreeLancer();
                fr.pack();
                
                new FrameFreeLancer().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane TxtA_affectationDetails;
    private javax.swing.JTextArea affectation;
    private javax.swing.JTextArea comment_project;
    private javax.swing.JComboBox domaineForTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JList sous_domainesList;
    public static javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_fname;
    private javax.swing.JTextField tf_lname;
    private javax.swing.JPasswordField tf_pwd;
    // End of variables declaration//GEN-END:variables
}
