/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.gui;

import java.awt.Color;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Blob;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import pidev.dao.FreelancerDAO;
import pidev.dao.GradeDAO;
import pidev.dao.UserDAO;
import pidev.entities.Freelancer;
import pidev.entities.Grade;
import pidev.entities.User;
import pidev.interfaces.IFreelancerDAO;
import pidev.interfaces.IGradeDAO;
import pidev.interfaces.IUserDAO;

/**
 *
 * @author HP
 */
public class FrameFormulaire extends javax.swing.JFrame {
    URL url;
    /**
     * Creates new form FrameFormulaire
     */
    public FrameFormulaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btn_cv = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_lastName = new javax.swing.JTextField();
        tf_firstName = new javax.swing.JTextField();
        jL_pieceJointe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(550, 600));
        setPreferredSize(new java.awt.Dimension(550, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 140, 100, 30);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 180, 90, 30);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 220, 70, 30);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 300, 80, 30);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setText("Date of Birth");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 260, 110, 30);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 340, 90, 30);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Create a free Account");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 70, 270, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/téléchargement.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(5500, 2500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1060, 120);

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel9.setText("Curriculum Vitae");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 380, 130, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(220, 190, 170, 28);

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Get Started !");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 409, 170, 40);

        btn_cv.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btn_cv.setText("Choose File");
        btn_cv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cvActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cv);
        btn_cv.setBounds(220, 310, 170, 31);

        jPasswordField1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(220, 270, 170, 30);

        jTextField4.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(220, 230, 170, 30);

        tf_email.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jPanel1.add(tf_email);
        tf_email.setBounds(220, 150, 170, 30);

        tf_lastName.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jPanel1.add(tf_lastName);
        tf_lastName.setBounds(220, 110, 170, 30);

        tf_firstName.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        tf_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_firstNameActionPerformed(evt);
            }
        });
        jPanel1.add(tf_firstName);
        tf_firstName.setBounds(220, 70, 170, 30);

        jL_pieceJointe.setFont(new java.awt.Font("Century Schoolbook", 0, 10)); // NOI18N
        jPanel1.add(jL_pieceJointe);
        jL_pieceJointe.setBounds(71, 350, 320, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 70, 410, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_firstNameActionPerformed

    private void btn_cvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cvActionPerformed
        JFileChooser chooser = new JFileChooser();
        int option = chooser.showOpenDialog(null);
        if(option == JFileChooser.APPROVE_OPTION){
            try{
                url = chooser.getSelectedFile().toURL();
                System.out.println(url);
                jL_pieceJointe.setText(url.toString());

            }
            catch(MalformedURLException exception){
                System.out.println("The URL was malformed ... ");
            }
        }
    }//GEN-LAST:event_btn_cvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IUserDAO userdao = UserDAO.getInstance();
        String firstName = tf_firstName.getText();
        String lastName = tf_lastName.getText();
        String email = tf_email.getText();
        String format = "dd/MM/yyyy";
        SimpleDateFormat formater = new SimpleDateFormat(format);
        Date dd = jDateChooser1.getDate();
        String d= (formater.format(dd)).toString();
        String userName = jTextField4.getText();
        String password = jPasswordField1.getText();
        //Blob f = (Blob) chooser.getSelectedFile();
        if (firstName.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter your First Name", "Error Message", JOptionPane.ERROR_MESSAGE);
            tf_firstName.setBorder(BorderFactory.createLineBorder(Color.decode("#FE1B00")));
        }
        if (lastName.isEmpty())
        {
           JOptionPane.showMessageDialog(this,"Please enter your Last Name", "Error Message", JOptionPane.ERROR_MESSAGE);
           tf_lastName.setBorder(BorderFactory.createLineBorder(Color.decode("#FE1B00")));
         
        }
        if (email.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter your Email", "Error Message", JOptionPane.ERROR_MESSAGE);
           tf_email.setBorder(BorderFactory.createLineBorder(Color.decode("#FE1B00")));
        
        }
        if (d.isEmpty())
        if (userName.isEmpty())
        if (password.isEmpty())
            
            
        
        if(firstName.equals("") | lastName.equals("") | email.equals("") | d.equals("") | userName.equals("") | password.equals(""))
            JOptionPane.showMessageDialog(this, "Veuillez rempir tous les champs", "Error Message", JOptionPane.ERROR_MESSAGE);
        else if(userdao.comparebyEmail(email))
                 JOptionPane.showMessageDialog(this, "email existe déjà", "Error Message", JOptionPane.ERROR_MESSAGE);
        else if(userdao.comparebylogin(userName))
                JOptionPane.showMessageDialog(this, "login existe déjà", "Error Message", JOptionPane.ERROR_MESSAGE);
        else
        {
            User u1= new User(userName,email,password,firstName,lastName,d,0,0);
            userdao.insertUser_inscri(u1);
            User u2= userdao.findUserByLogin(userName);
            int a = u2.getId();
            Freelancer free = new Freelancer();
            free.setId(a);
            free.setCv(null);
            IFreelancerDAO fdao = FreelancerDAO.getInstance();
            fdao.insertFreeLancerFormulaire(free);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFormulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFormulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFormulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFormulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFormulaire().setVisible(true);
            }
        });
    }
JFileChooser chooser = new JFileChooser();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cv;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jL_pieceJointe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_firstName;
    private javax.swing.JTextField tf_lastName;
    // End of variables declaration//GEN-END:variables
}
