/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.gui;

import pidev.dao.UserDAO;
import pidev.entities.User;
import pidev.interfaces.IUserDAO;

/**
 *
 * @author HP
 */
public class FrameUsers extends javax.swing.JFrame {

    /**
     * Creates new form FrameUsers
     */
    public FrameUsers() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Activate/Disactivate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 51));
        jTable1.setModel(new ListUsers());
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("All Users", jScrollPane1);

        jTable2.setModel(new ListFreelancer());
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("FreLancers", jScrollPane2);

        jTable3.setModel(new ListJobowner());
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane1.addTab("JobOwners", jScrollPane3);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 51));
        jButton4.setText("Back to Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jButton3)
                .addGap(65, 65, 65)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int a=jTable1.getSelectedRow();
       int b=jTable2.getSelectedRow();
       int c=jTable3.getSelectedRow();
         if (a!=-1)
         {       
         
             IUserDAO udao = UserDAO.getInstance();
             udao.deleteUser( Integer.parseInt(jTable1.getValueAt(a, 0).toString()));
             
             jTable1.setModel(new ListUsers());
             jTable2.setModel(new ListFreelancer());
             jTable3.setModel(new ListJobowner());
        }
         if (b!=-1)
{       
         
             IUserDAO udao = UserDAO.getInstance();
             udao.deleteUser( Integer.parseInt(jTable2.getValueAt(b, 0).toString()));
             
             jTable1.setModel(new ListUsers());
             jTable2.setModel(new ListFreelancer());
             jTable3.setModel(new ListJobowner());
        }
         if (c!=-1)
{       
         
             IUserDAO udao = UserDAO.getInstance();
             udao.deleteUser( Integer.parseInt(jTable3.getValueAt(c, 0).toString()));
             
             jTable1.setModel(new ListUsers());
             jTable2.setModel(new ListFreelancer());
             jTable3.setModel(new ListJobowner());
        }         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int a=jTable1.getSelectedRow();
        int b=jTable2.getSelectedRow();
       int c=jTable3.getSelectedRow();
       IUserDAO udao = UserDAO.getInstance();
            User us = new User(); 
       if(a!=-1)
        {
            
            us=udao.FindUserById(Integer.parseInt(jTable1.getValueAt(a, 0).toString()));
           if((jTable1.getValueAt(a, 6).toString()).compareTo("Yes")==0)
           {
               us.setEstActive(0);}
               else
           {
               us.setEstActive(1);
           }
           udao.updateUser(us);
            jTable1.setModel(new ListUsers());
             jTable2.setModel(new ListFreelancer());
             jTable3.setModel(new ListJobowner());
        }
        if(b!=-1)
        {
            
            us=udao.FindUserById(Integer.parseInt(jTable2.getValueAt(b, 0).toString()));
           if((jTable2.getValueAt(b, 6).toString()).compareTo("Yes")==0)
           {
               us.setEstActive(0);}
               else
           {
               us.setEstActive(1);
           }
           udao.updateUser(us);
            jTable1.setModel(new ListUsers());
             jTable2.setModel(new ListFreelancer());
             jTable3.setModel(new ListJobowner());
            
        }
        if(c!=-1)
        {
            
            us=udao.FindUserById(Integer.parseInt(jTable3.getValueAt(c, 0).toString()));
           if((jTable3.getValueAt(c, 6).toString()).compareTo("Yes")==0)
           {
               us.setEstActive(0);}
               else
           {
               us.setEstActive(1);
           }
           udao.updateUser(us);
             jTable1.setModel(new ListUsers());
             jTable2.setModel(new ListFreelancer());
             jTable3.setModel(new ListJobowner());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    FrameAdministrateur fr = new FrameAdministrateur();
    fr.show(true);
    this.show(false);
    
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
