/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.gui;

import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import pidev.dao.AffectationDAO;
import pidev.dao.DomaineDAO;
import pidev.dao.ProjetDAO;
import pidev.dao.UserDAO;
import pidev.entities.Affectation;
import pidev.entities.Domaine;
import pidev.entities.Freelancer;
import pidev.entities.Projet;
import pidev.entities.User;
import pidev.interfaces.IAffectationDAO;
import pidev.interfaces.IDomaineDAO;
import pidev.interfaces.IProjetDAO;
import pidev.interfaces.IUserDAO;
import pidev.modeles.ModeleFreelancerRequests;
import pidev.modeles.ModeleManageProjets;

/**
 *
 * @author HP
 */
public class FrameJobOwner extends javax.swing.JFrame {
    public static int id_login;
    /**
     * Creates new form FrameJobOwner
     */
    public FrameJobOwner() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchPro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tf_pwd = new javax.swing.JPasswordField();
        tf_lname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_fname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        detailsProjectSelectedTxt = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Details_projetTA = new javax.swing.JTextArea();
        nom_projetTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        domeineProjetCBO = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabEmail = new javax.swing.JLabel();
        jLabNom = new javax.swing.JLabel();
        jLabPrenom = new javax.swing.JLabel();
        jLabDateBirth = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(707, 417));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setText("Welcome JobOwner");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(435, 10, 190, 22);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel2.setText("You have 341 Tokens");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 40, 140, 17);

        SearchPro.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        getContentPane().add(SearchPro);
        SearchPro.setBounds(480, 80, 148, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/hardware-icon-search-button.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 80, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/logout.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 10, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/téléchargement.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 790, 130);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setLayout(null);

        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 130, 130);

        jButton1.setText("Choisir Image");
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 140, 130, 23);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        tf_lname.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Email");

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Password");

        tf_fname.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("First Name");

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Date Of Birth");

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Last Name");

        tf_email.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(tf_lname)
                                .addComponent(tf_email)
                                .addComponent(tf_pwd))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(320, 10, 340, 230);

        jTabbedPane1.addTab("My Profile", jPanel2);

        jPanel3.setLayout(null);

        jTable1.setModel(new ModeleManageProjets(3));
        jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 610, 100);

        jLabel10.setText("Details");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 190, 40, 14);

        jButton3.setText("Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(30, 110, 540, 40);

        jScrollPane5.setViewportView(detailsProjectSelectedTxt);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(60, 180, 510, 170);

        jTabbedPane1.addTab("Manage Projects", jPanel3);

        jPanel4.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        Details_projetTA.setColumns(20);
        Details_projetTA.setRows(5);
        jScrollPane3.setViewportView(Details_projetTA);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(110, 120, 480, 160);
        jPanel6.add(nom_projetTxt);
        nom_projetTxt.setBounds(110, 20, 160, 30);

        jLabel6.setText("Name");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(20, 20, 60, 20);

        jLabel8.setText("Domain");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(20, 70, 70, 20);

        jLabel9.setText("Details");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(20, 110, 60, 20);

        IDomaineDAO ddao = DomaineDAO.getInstance();

        for (Domaine d:ddao.DisplayAllDomaines()){

            domeineProjetCBO.addItem(d);
        }
        jPanel6.add(domeineProjetCBO);
        domeineProjetCBO.setBounds(110, 70, 160, 30);

        jButton4.setText("Add Project");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(110, 300, 140, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 610, 350);

        jTabbedPane1.addTab("Add Projects", jPanel4);
        jTabbedPane1.addTab("Messages", jPanel5);

        jPanel7.setLayout(null);

        // XX113XX Id jobowner here
        jTable2.setModel(new ModeleFreelancerRequests(3));
        jTable2.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jPanel7.add(jScrollPane4);
        jScrollPane4.setBounds(-1, 5, 610, 100);

        jButton6.setText("Accept");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(40, 300, 110, 40);

        jButton7.setText("Reject");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(350, 300, 110, 40);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Personal Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 14))); // NOI18N
        jPanel8.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel20.setText("Email");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(30, 90, 50, 20);

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel12.setText("Last Name");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(30, 50, 90, 20);

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel18.setText("First Name");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(30, 30, 90, 20);

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel19.setText("Date Of Birth");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(30, 70, 110, 20);

        jLabEmail.setText(" ");
        jPanel8.add(jLabEmail);
        jLabEmail.setBounds(180, 90, 220, 14);

        jLabNom.setText(" ");
        jPanel8.add(jLabNom);
        jLabNom.setBounds(180, 30, 210, 14);

        jLabPrenom.setText(" ");
        jPanel8.add(jLabPrenom);
        jLabPrenom.setBounds(180, 50, 210, 14);

        jLabDateBirth.setText(" ");
        jPanel8.add(jLabDateBirth);
        jLabDateBirth.setBounds(180, 70, 210, 14);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(40, 160, 420, 140);
        jPanel8.getAccessibleContext().setAccessibleName("*Personal Informations");

        jButton5.setText("Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);
        jButton5.setBounds(50, 110, 400, 40);

        jButton8.setText("completed");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8);
        jButton8.setBounds(200, 340, 100, 40);

        jTabbedPane1.addTab("FreeLancers' Requests", jPanel7);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 130, 790, 400);

        jMenu1.setForeground(new java.awt.Color(0, 102, 102));
        jMenu1.setText("Profile");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Exit");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pidev/gui/images/exit.png"))); // NOI18N
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 102, 102));
        jMenu2.setText("Messages");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Inbox");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Sent Mail");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 102, 102));
        jMenu3.setText("FreeLancers");

        jMenuItem5.setText("See all FreeLancers");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 102, 102));
        jMenu4.setText("Settings");

        jMenuItem1.setText("Edit Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(0, 102, 102));
        jMenu5.setText("Help");

        jMenuItem2.setText("Help Contents");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);
        jMenu5.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("About");
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Version Information");
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        System.exit(0);    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String format = "dd/MM/yyyy";
        SimpleDateFormat formater = new SimpleDateFormat(format);
        java.util.Date dd = jDateChooser1.getDate();
        String d = (formater.format(dd)).toString();

        String name = tf_fname.getText();
        String lname = tf_lname.getText();
        String email = tf_email.getText();
        String pwd = tf_pwd.getText();

        User u = new User();
        u.setId(20);
        u.setPrenom(name);
        u.setNom(lname);
        u.setEmail(email);
        u.setDate_naissance(d);
        u.setPassword(pwd);
        IUserDAO udao = UserDAO.getInstance();
        udao.updateUserProfile(u);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           int a=jTable2.getSelectedRow();
        if (a!=-1)
         {       
             Domaine d = new Domaine(2,"Non");
            Affectation affectation = new Affectation();
            affectation = (Affectation)jTable2.getValueAt(a, 5);
            
            IAffectationDAO affffdao = AffectationDAO.getInstance();
            affffdao.updateAcceptAffectation(affectation.getId(),2);
                JOptionPane.showMessageDialog(this, "Affectation Modifier", "Domaines", JOptionPane.INFORMATION_MESSAGE);
                
                jTable2.setValueAt(d, a, 3);
       
         }
         else{
             Component sadds = null;
             JOptionPane.showMessageDialog(this, "Veillez selectionner une donnée", "Domaines", JOptionPane.ERROR_MESSAGE);
         } 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (nom_projetTxt.getText()!="" && Details_projetTA.getText()!=""){
        
            Domaine d = (Domaine) domeineProjetCBO.getSelectedItem();
            //XX113XX user here
            User u = new User(1, "ss", "ss", "ss", "ss", "ss", "ss", "ss", 1, "ss", 0);
            
            IProjetDAO pdao = ProjetDAO.getInstance();
            Projet p = new Projet(nom_projetTxt.getText(), Details_projetTA.getText(), u, d);
            pdao.insertProjet(p);
            
        
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int a=jTable1.getSelectedRow();
        
         if (a!=-1)
         {       
            
            Projet projet = new Projet();
            projet = (Projet)jTable1.getValueAt(a, 3);
             detailsProjectSelectedTxt.setText(projet.getDetails());
        
         }
         else{
             Component sadds = null;
             JOptionPane.showMessageDialog(sadds, "Veillez selectionner un projet", "Domaines", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  int a=jTable2.getSelectedRow();
        
         if (a!=-1)
         {       
             Domaine d = new Domaine(1,"Non");
            Affectation affectation = new Affectation();
            affectation = (Affectation)jTable2.getValueAt(a, 5);
            
            IAffectationDAO affffdao = AffectationDAO.getInstance();
            affffdao.updateAcceptAffectation(affectation.getId(),1);
                JOptionPane.showMessageDialog(this, "Affectation Modifier", "Domaines", JOptionPane.INFORMATION_MESSAGE);
                
                jTable2.setValueAt(d, a, 3);
       
         }
         else{
             Component sadds = null;
             JOptionPane.showMessageDialog(this, "Veillez selectionner une donnée", "Domaines", JOptionPane.ERROR_MESSAGE);
         }    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int a=jTable2.getSelectedRow();
        
         if (a!=-1)
         {       
            Affectation affectation = new Affectation();
            affectation = (Affectation)jTable2.getValueAt(a, 5);
            
             jLabNom.setText(affectation.getFreelancer().getNom());
             jLabPrenom.setText(affectation.getFreelancer().getPrenom());
             jLabDateBirth.setText(affectation.getFreelancer().getDate_naissance());
             jLabEmail.setText(affectation.getFreelancer().getEmail());
 
         }
         else
              JOptionPane.showMessageDialog(this, "Selectionner une requete", "FreeRequests", JOptionPane.ERROR_MESSAGE);
             
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
     FrameFindetEvaluer fe1 = new FrameFindetEvaluer();
     fe1.setVisible(true);
     fe1.remplirTxt(SearchPro.getText());
    
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int a = jTable2.getSelectedRow();
        Affectation affectation = new Affectation();
        //Freelancer free = new Freelancer();
        User job = new User();

        IUserDAO user = UserDAO.getInstance();

        //XX113XX
        job = user.FindUserById(id_login);
        int amount;
        if (a != -1) {
            try {
                amount = Integer.parseInt(JOptionPane.showInputDialog("Enter the amount to be transfered", 0));
                if (amount <= 0) {
                    JOptionPane.showMessageDialog(this, "Enter a proper amount ", "Alert", JOptionPane.ERROR_MESSAGE);
                } else if (job.getTokens() > amount) {

                    affectation = (Affectation) jTable2.getValueAt(a, 5);

                    Freelancer free = affectation.getFreelancer();
                    user.updateTokensUser(job, free, amount);
                } else {
                    JOptionPane.showMessageDialog(this, "You don't have enough tokens", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Enter a proper Amount", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a freelancer", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       int a = jTable2.getSelectedRow();
        if (a!=-1){
            if((jTable2.getValueAt(a, 3).toString()).compareTo("completed")==0)
            {
                jButton7.setEnabled(false);
                jButton8.setEnabled(false);
                jButton6.setEnabled(false);
            }
            else if ((jTable2.getValueAt(a, 3).toString()).compareTo("Rejected")==0){
                jButton8.setEnabled(false);
                jButton7.setEnabled(false);
                jButton6.setEnabled(true);

            }
            else if (((jTable2).getValueAt(a, 3).toString()).compareTo("Accepted")==0){
                jButton6.setEnabled(false);
                jButton8.setEnabled(true);
                jButton7.setEnabled(true);
                
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJobOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJobOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJobOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJobOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJobOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Details_projetTA;
    private javax.swing.JTextField SearchPro;
    private javax.swing.JEditorPane detailsProjectSelectedTxt;
    private javax.swing.JComboBox domeineProjetCBO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabDateBirth;
    private javax.swing.JLabel jLabEmail;
    private javax.swing.JLabel jLabNom;
    private javax.swing.JLabel jLabPrenom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nom_projetTxt;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_fname;
    private javax.swing.JTextField tf_lname;
    private javax.swing.JPasswordField tf_pwd;
    // End of variables declaration//GEN-END:variables
}
